/**
 * Represents a single work experience entry stored in the database.
 */
export type WorkExperienceEntity = {
  /** Auto-incremented unique identifier */
  id: number;
  /** Company name */
  companyName: string;
  /** Job title */
  jobTitle: string;
  /** Workplace city location */
  workCityLocation: string;
  /** Job start date */
  startDate: Date;
  /** Job end date */
  endDate: Date;
  /** Job description */
  description: string;
};

/**
 * Payload for creating a new work experience.
 * Omits the `id` field since it's generated by the DB.
 *
 * Used for POST request bodies.
 */
export type WorkExperiencePayload = Omit<WorkExperienceEntity, "id">;
